namespace iReverse_UniSPD_FRP.UniSPD
{
    internal static class Uni_CMD
    {
        public static int HDLC_HEADER = 0x7E;
        public static int HDLC_ESCAPE = 0x7D;

        public enum BSL
        {
            CMD_CONNECT = 0x0,

            CMD_START_DATA = 0x1,
            CMD_MIDST_DATA = 0x2,
            CMD_END_DATA = 0x3,
            CMD_EXEC_DATA = 0x4,

            CMD_NORMAL_RESET = 0x5,
            CMD_READ_FLASH = 0x6,
            CMD_READ_CHIP_TYPE = 0x7,
            CMD_READ_NVITEM = 0x8,
            CMD_CHANGE_BAUD = 0x9,
            CMD_ERASE_FLASH = 0xA,
            CMD_REPARTITION = 0xB,
            CMD_READ_FLASH_TYPE = 0xC,
            CMD_READ_FLASH_INFO = 0xD,
            CMD_READ_SECTOR_SIZE = 0xF,
            CMD_READ_START = 0x10,
            CMD_READ_MIDST = 0x11,
            CMD_READ_END = 0x12,

            CMD_KEEP_CHARGE = 0x13,
            CMD_EXTTABLE = 0x14,
            CMD_READ_FLASH_UID = 0x15,
            CMD_READ_SOFTSIM_EID = 0x16,
            CMD_POWER_OFF = 0x17,
            CMD_CHECK_ROOT = 0x19,
            CMD_READ_CHIP_UID = 0x1A,
            CMD_ENABLE_WRITE_FLASH = 0x1B,
            CMD_ENABLE_SECUREBOOT = 0x1C,
            CMD_IDENTIFY_START = 0x1D,
            CMD_IDENTIFY_END = 0x1E,
            CMD_READ_CU_REF = 0x1F,
            CMD_READ_REFINFO = 0x20,
            CMD_DISABLE_TRANSCODE = 0x21,
            CMD_WRITE_DATETIME = 0x22,
            CMD_CUST_DUMMY = 0x23,
            CMD_READ_RF_TRANSCEIVER_TYPE = 0x24,
            CMD_SET_DEBUGINFO = 0x25,
            CMD_DDR_CHECK = 0x26,
            CMD_SELF_REFRESH = 0x27,
            CMD_WRITE_RAW_DATA_ENABLE = 0x28,
            CMD_READ_NAND_BLOCK_INFO = 0x29,
            CMD_SET_FIRST_MODE = 0x2A,
            CMD_READ_PARTITION = 0x2D,
            CMD_DLOAD_RAW_START = 0x31,
            CMD_WRITE_FLUSH_DATA = 0x32,
            CMD_DLOAD_RAW_START2 = 0x33,
            CMD_READ_LOG = 0x35,
            CMD_CHECK_BAUD = 0x7E,
            CMD_END_PROCESS = 0x7F,
            REP_ACK = 0x80,
            REP_VER = 0x81,
            REP_INVALID_CMD = 0x82,
            REP_UNKNOW_CMD = 0x83,
            REP_OPERATION_FAILED = 0x84,
            REP_NOT_SUPPORT_BAUDRATE = 0x85,
            REP_DOWN_NOT_START = 0x86,
            REP_DOWN_MULTI_START = 0x87,
            REP_DOWN_EARLY_END = 0x88,
            REP_DOWN_DEST_ERROR = 0x89,
            REP_DOWN_SIZE_ERROR = 0x8A,
            REP_VERIFY_ERROR = 0x8B,
            REP_NOT_VERIFY = 0x8C,
            PHONE_NOT_ENOUGH_MEMORY = 0x8D,
            PHONE_WAIT_INPUT_TIMEOUT = 0x8E,
            PHONE_SUCCEED = 0x8F,
            PHONE_VALID_BAUDRATE = 0x90,
            PHONE_REPEAT_CONTINUE = 0x91,
            PHONE_REPEAT_BREAK = 0x92,
            REP_READ_FLASH = 0x93,
            REP_READ_CHIP_TYPE = 0x94,
            REP_READ_NVITEM = 0x95,
            REP_INCOMPATIBLE_PARTITION = 0x96,
            REP_SIGN_VERIFY_ERROR = 0xA6,
            REP_READ_CHIP_UID = 0xAB,
            REP_READ_PARTITION = 0xBA,
            REP_READ_LOG = 0xBB,
            REP_UNSUPPORTED_COMMAND = 0xFE,
            REP_NOT_ENABLE_WRITE_FLASH = 0xAC
        }
    }
}
